### ISSUE TITLE
minor form field validation icons bug on iOS

### ISSUE THREAD

**Issue by cvrebert** [owenversteeg/min-bootstrap-plugin#1]
On iOS 7.1, by tapping in an unfortunate place near the validation state icon, it's possible to enter what seems to be a text field to the right of the icon. Attempting to type while in this field seems to have no effect.
Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/419884/3710537/3de67582-1494-11e4-8c0b-5a287e40393d.jpg)
Note the position of the cursor (blue vertical line).

**Comment by owenversteeg** [comment]
Fixed. Now I have to fix the bug you just brought to my attention - the left text being squished by the input.

Thanks for reporting all these bugs - it really helps!
