### ISSUE TITLE
form field validation icons not vertically centered

### ISSUE THREAD

**Issue by cvrebert** [owenversteeg/min-bootstrap-plugin#2]
Note how they don't align with the placeholder text.
![shot](https://cloud.githubusercontent.com/assets/419884/3712790/00d37f40-1535-11e4-9f7c-8fd712e4aad4.png)

**Comment by owenversteeg** [comment]
Huh, what browser/OS combo is this?

**Comment by cvrebert** [comment]
Chrome on Mac OS X

**Comment by owenversteeg** [comment]
Linux Chrome36 looks good, XP Chrome36 looks good, and OSX Chrome36 looks good.
