### ISSUE TITLE
input group in inline form displays incorrectly

### ISSUE THREAD

**Issue by cvrebert** [owenversteeg/min-bootstrap-plugin#20]
![inline-form-input-group](https://cloud.githubusercontent.com/assets/419884/3783094/06488d62-19a9-11e4-9515-9c614e1785a5.png)

**Comment by owenversteeg** [comment]
That's because this is a feature in Min core. Take a look at the [Min docs](http://minfwk.com/docs.html) for the correct syntax. Thanks anyway - I should've noted in the index.html that Min core's syntax is usually different.
